const DEFAULT_KIMI_BASE_URL = 'https://api.moonshot.cn/v1';
const DEFAULT_KIMI_MODEL = 'kimi-k2.5';

function buildKimiConfigToml({ apiKey, baseUrl, model }) {
    const lines = [
        '# Generated by XEnsemble — BYOK provider for Kimi Code',
        `default_model = ${JSON.stringify(model)}`,
        '',
        '[providers.kimi]',
        'type = "kimi"',
        `base_url = ${JSON.stringify(baseUrl)}`,
        `api_key = ${JSON.stringify(apiKey)}`,
        '',
        '[models.kimi-default]',
        'provider = "kimi"',
        `model = ${JSON.stringify(model)}`,
        'max_context_size = 256000',
        '',
    ];
    return `${lines.join('\n')}\n`;
}

function shellWriteConfigScript(configToml) {
    const encoded = Buffer.from(configToml, 'utf8').toString('base64');
    return [
        'set -e',
        'mkdir -p "$HOME/.kimi"',
        `printf '%s' ${JSON.stringify(encoded)} | base64 -d > "$HOME/.kimi/config.toml"`,
    ].join('\n');
}

module.exports = {
    DEFAULT_KIMI_BASE_URL,
    DEFAULT_KIMI_MODEL,
    buildKimiConfigToml,
    shellWriteConfigScript,
};
