/** Built-in agent catalog — synced on DB init via INSERT OR IGNORE + UPDATE for cmd/args/env. */

const DEFAULT_AGENTS = [
    {
        id: 'kimi-code',
        name: 'Kimi Code',
        cmd: 'kimi',
        args: [],
        // Kimi Code authenticates via `kimi login` / config.toml — no BYOK env injection.
        env_required: [],
    },
    {
        id: 'claude-code',
        name: 'Claude Code',
        cmd: 'claude',
        args: [],
        env_required: ['ANTHROPIC_API_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'CLAUDE_CONFIG_DIR',
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'cursor',
        name: 'Cursor Agent',
        cmd: 'agent',
        args: [],
        env_required: [],
    },
    {
        id: 'opencode',
        name: 'OpenCode',
        cmd: 'opencode',
        args: [],
        env_required: ['ANTHROPIC_API_KEY', 'OPENAI_API_KEY'],
    },
    {
        id: 'amp',
        name: 'AMP',
        cmd: 'amp',
        args: [],
        env_required: ['AMP_API_KEY'],
    },
    {
        id: 'cline',
        name: 'Cline',
        cmd: 'cline',
        args: [],
        env_required: ['ANTHROPIC_API_KEY'],
    },
    {
        id: 'codebuddy',
        name: 'CodeBuddy Code',
        cmd: 'codebuddy',
        args: [],
        env_required: [],
    },
    {
        id: 'droid',
        name: 'Factory Droid',
        cmd: 'droid',
        args: [],
        env_required: [],
    },
    {
        id: 'glm-agent',
        name: 'GLM Agent',
        cmd: 'zai',
        args: [],
        env_required: ['ZAI_API_KEY'],
    },
    {
        id: 'qoder',
        name: 'Qoder CLI',
        cmd: 'qodercli',
        args: [],
        env_required: ['QODER_PERSONAL_ACCESS_TOKEN'],
    },
    {
        id: 'qwen-code',
        name: 'Qwen Code',
        cmd: 'qwen',
        args: [],
        env_required: ['DASHSCOPE_API_KEY'],
    },
    {
        id: 'minimax-cli',
        name: 'MiniMax CLI',
        cmd: 'mmx',
        args: [],
        env_required: ['MINIMAX_API_KEY'],
    },
    {
        id: 'pi',
        name: 'Pi',
        cmd: 'pi',
        args: [],
        env_required: ['ANTHROPIC_API_KEY', 'OPENAI_API_KEY'],
    },
    {
        id: 'github-copilot',
        name: 'GitHub Copilot',
        cmd: 'copilot',
        args: [],
        env_required: [],
    },
    {
        id: 'commandcode',
        name: 'CommandCode',
        cmd: 'commandcode',
        args: [],
        env_required: ['COHERE_API_KEY'],
    },
    {
        id: 'hermes',
        name: 'Hermes',
        cmd: 'hermes',
        args: ['chat', '--ignore-user-config', '--provider', 'openrouter'],
        env_required: ['OPENROUTER_API_KEY'],
    },
    {
        id: 'openclaw',
        name: 'OpenClaw',
        cmd: 'openclaw',
        args: [],
        env_required: ['OPENCLAW_KEY'],
    },
];

module.exports = { DEFAULT_AGENTS };
