/** Built-in agent catalog — synced on DB init via INSERT OR IGNORE + UPDATE for cmd/args/env. */

const DEFAULT_AGENTS = [
    {
        id: 'kimi-code',
        name: 'Kimi Code',
        cmd: 'kimi',
        args: [],
        // Kimi Code authenticates via `kimi login` / config.toml — no BYOK env injection.
        env_required: [],
        resume: {
            level: 'L2',
            stateEnv: 'KIMI_CODE_HOME',
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'claude-code',
        name: 'Claude Code',
        cmd: 'claude',
        args: [],
        env_required: ['ANTHROPIC_API_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'CLAUDE_CONFIG_DIR',
            resumeArgs: ['--continue'],
            resumeCheckSubdir: 'sessions',
        },
    },
    {
        id: 'cursor',
        name: 'Cursor Agent',
        cmd: 'agent',
        args: [],
        env_required: [],
        resume: {
            level: 'L2',
            stateEnv: 'CURSOR_DATA_DIR',
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'opencode',
        name: 'OpenCode',
        cmd: 'opencode',
        args: [],
        env_required: ['ANTHROPIC_API_KEY', 'OPENAI_API_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'XDG_DATA_HOME',
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'amp',
        name: 'AMP',
        cmd: 'amp',
        args: [],
        env_required: ['AMP_API_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'XENSEMBLE_STATE_DIR',
            resumeArgs: ['last'],
        },
    },
    {
        id: 'cline',
        name: 'Cline',
        cmd: 'cline',
        args: [],
        env_required: ['ANTHROPIC_API_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'CLINE_DATA_DIR',
        },
    },
    {
        id: 'codebuddy',
        name: 'CodeBuddy Code',
        cmd: 'codebuddy',
        args: [],
        env_required: [],
        resume: {
            level: 'L2',
            stateEnv: 'CODEBUDDY_CONFIG_DIR',
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'droid',
        name: 'Factory Droid',
        cmd: 'droid',
        args: [],
        env_required: [],
        resume: {
            level: 'L2',
            stateEnv: 'FACTORY_HOME_OVERRIDE',
            resumeArgs: ['--resume'],
        },
    },
    {
        id: 'glm-agent',
        name: 'GLM Agent',
        cmd: 'zai',
        args: [],
        env_required: ['ZAI_API_KEY'],
        resume: {
            level: 'L2',
            redirectHome: true,
        },
    },
    {
        id: 'qoder',
        name: 'Qoder CLI',
        cmd: 'qodercli',
        args: [],
        env_required: ['QODER_PERSONAL_ACCESS_TOKEN'],
        resume: {
            level: 'L2',
            stateArgs: ['--config-dir'],
            resumeArgs: ['--continue'],
            resumeCheckSubdir: 'logs/sessions',
        },
    },
    {
        id: 'qwen-code',
        name: 'Qwen Code',
        cmd: 'qwen',
        args: [],
        env_required: ['DASHSCOPE_API_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'QWEN_HOME',
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'minimax-cli',
        name: 'MiniMax CLI',
        cmd: 'mmx',
        args: [],
        env_required: ['MINIMAX_API_KEY'],
    },
    {
        id: 'pi',
        name: 'Pi',
        cmd: 'pi',
        args: [],
        env_required: ['ANTHROPIC_API_KEY', 'OPENAI_API_KEY'],
        resume: {
            level: 'L2',
            stateArgs: ['--session-dir'],
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'github-copilot',
        name: 'GitHub Copilot',
        cmd: 'copilot',
        args: [],
        env_required: [],
    },
    {
        id: 'commandcode',
        name: 'CommandCode',
        cmd: 'commandcode',
        args: [],
        env_required: ['COHERE_API_KEY'],
        resume: {
            level: 'L2',
            redirectHome: true,
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'hermes',
        name: 'Hermes',
        cmd: 'hermes',
        args: ['chat', '--ignore-user-config', '--provider', 'openrouter'],
        env_required: ['OPENROUTER_API_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'HERMES_HOME',
            resumeArgs: ['--continue'],
        },
    },
    {
        id: 'openclaw',
        name: 'OpenClaw',
        cmd: 'openclaw',
        args: [],
        env_required: ['OPENCLAW_KEY'],
        resume: {
            level: 'L2',
            stateEnv: 'OPENCLAW_STATE_DIR',
        },
    },
];

module.exports = { DEFAULT_AGENTS };
